const keybinds = [
    {
        command: "cursorHome",
        key: "ctrl+b",
        when: "neovim.mode == cmdline",
    },
    {
        command: "cursorEnd",
        key: "ctrl+e",
        when: "neovim.mode == cmdline",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+h",
        when: "neovim.mode == cmdline",
        args: "<C-h>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+w",
        when: "neovim.mode == cmdline",
        args: "<C-w>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+u",
        when: "neovim.mode == cmdline",
        args: "<C-u>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 0",
        when: "neovim.mode == cmdline",
        args: "<C-r>0",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 1",
        when: "neovim.mode == cmdline",
        args: "<C-r>1",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 2",
        when: "neovim.mode == cmdline",
        args: "<C-r>2",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 3",
        when: "neovim.mode == cmdline",
        args: "<C-r>3",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 4",
        when: "neovim.mode == cmdline",
        args: "<C-r>4",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 5",
        when: "neovim.mode == cmdline",
        args: "<C-r>5",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 6",
        when: "neovim.mode == cmdline",
        args: "<C-r>6",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 7",
        when: "neovim.mode == cmdline",
        args: "<C-r>7",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 8",
        when: "neovim.mode == cmdline",
        args: "<C-r>8",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r 9",
        when: "neovim.mode == cmdline",
        args: "<C-r>9",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r shift+'",
        when: "neovim.mode == cmdline",
        args: '<C-r>"',
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r shift+5",
        when: "neovim.mode == cmdline",
        args: "<C-r>%",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r shift+3",
        when: "neovim.mode == cmdline",
        args: "<C-r>#",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r shift+8",
        when: "neovim.mode == cmdline",
        args: "<C-r>*",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r shift+=",
        when: "neovim.mode == cmdline",
        args: "<C-r>+",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r /",
        when: "neovim.mode == cmdline",
        args: "<C-r>/",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r shift+;",
        when: "neovim.mode == cmdline",
        args: "<C-r>:",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r -",
        when: "neovim.mode == cmdline",
        args: "<C-r>-",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r .",
        when: "neovim.mode == cmdline",
        args: "<C-r>.",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r =",
        when: "neovim.mode == cmdline",
        args: "<C-r>=",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r a",
        when: "neovim.mode == cmdline",
        args: "<C-r>a",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r b",
        when: "neovim.mode == cmdline",
        args: "<C-r>b",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r c",
        when: "neovim.mode == cmdline",
        args: "<C-r>c",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r d",
        when: "neovim.mode == cmdline",
        args: "<C-r>d",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r e",
        when: "neovim.mode == cmdline",
        args: "<C-r>e",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r f",
        when: "neovim.mode == cmdline",
        args: "<C-r>f",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r g",
        when: "neovim.mode == cmdline",
        args: "<C-r>g",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r h",
        when: "neovim.mode == cmdline",
        args: "<C-r>h",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r i",
        when: "neovim.mode == cmdline",
        args: "<C-r>i",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r j",
        when: "neovim.mode == cmdline",
        args: "<C-r>j",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r k",
        when: "neovim.mode == cmdline",
        args: "<C-r>k",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r l",
        when: "neovim.mode == cmdline",
        args: "<C-r>l",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r m",
        when: "neovim.mode == cmdline",
        args: "<C-r>m",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r n",
        when: "neovim.mode == cmdline",
        args: "<C-r>n",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r o",
        when: "neovim.mode == cmdline",
        args: "<C-r>o",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r p",
        when: "neovim.mode == cmdline",
        args: "<C-r>p",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r q",
        when: "neovim.mode == cmdline",
        args: "<C-r>q",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r r",
        when: "neovim.mode == cmdline",
        args: "<C-r>r",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r s",
        when: "neovim.mode == cmdline",
        args: "<C-r>s",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r t",
        when: "neovim.mode == cmdline",
        args: "<C-r>t",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r u",
        when: "neovim.mode == cmdline",
        args: "<C-r>u",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r v",
        when: "neovim.mode == cmdline",
        args: "<C-r>v",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r w",
        when: "neovim.mode == cmdline",
        args: "<C-r>w",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r x",
        when: "neovim.mode == cmdline",
        args: "<C-r>x",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r y",
        when: "neovim.mode == cmdline",
        args: "<C-r>y",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r z",
        when: "neovim.mode == cmdline",
        args: "<C-r>z",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r ctrl+f",
        when: "neovim.mode == cmdline",
        args: "<C-r><C-f>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r ctrl+p",
        when: "neovim.mode == cmdline",
        args: "<C-r><C-p>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r ctrl+w",
        when: "neovim.mode == cmdline",
        args: "<C-r><C-w>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r ctrl+a",
        when: "neovim.mode == cmdline",
        args: "<C-r><C-a>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+r ctrl+l",
        when: "neovim.mode == cmdline",
        args: "<C-r><C-l>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+\\ e",
        when: "neovim.mode == cmdline",
        args: "<C-\\>e",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "down",
        when: "neovim.mode == cmdline",
        args: "<Down>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+n",
        when: "neovim.mode == cmdline",
        args: "<Down>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "up",
        when: "neovim.mode == cmdline",
        args: "<Up>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+p",
        when: "neovim.mode == cmdline",
        args: "<Up>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+l",
        when: "neovim.mode == cmdline",
        args: "<C-l>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+g",
        when: "neovim.mode == cmdline",
        args: "<C-g>",
    },
    {
        command: "vscode-neovim.send-cmdline",
        key: "ctrl+t",
        when: "neovim.mode == cmdline",
        args: "<C-t>",
    },
    {
        command: "vscode-neovim.complete-selection-cmdline",
        key: "tab",
        when: "neovim.mode == cmdline",
    },
];

module.exports = keybinds;
